# Generated by Codex on 2025-07-07
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('email_token', models.CharField(max_length=100, blank=True, null=True)),
                ('forget_password_token', models.CharField(max_length=100, blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('job_title', models.CharField(max_length=100, blank=True, null=True)),
                ('contract_type', models.CharField(max_length=100, blank=True, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('manager', models.CharField(max_length=100, blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=100, blank=True, null=True)),
                ('city', models.CharField(max_length=100, blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('zip_code', models.CharField(max_length=100, blank=True, null=True)),
                ('state', models.CharField(max_length=100, blank=True, null=True)),
                ('phone', models.CharField(max_length=100, blank=True, null=True)),
                ('language', models.CharField(max_length=10, blank=True, null=True)),
                ('timezone', models.CharField(max_length=100, blank=True, null=True)),
                ('currency', models.CharField(max_length=10, blank=True, null=True)),
                ('mfa_secret', models.CharField(max_length=100, blank=True, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connexion.department', null=True, blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, related_name='profile')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
