# Generated by Django 5.1.4 on 2025-07-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0002_alter_profile_department_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
