services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "443:443"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - DJANGO_SECRET_KEY=changeme
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres

  # mailpit:
  #   image: mailhog/mailhog
  #   ports:
  #     - "${FORWARD_MAILHOG_PORT:-8025}:8025"

    
volumes:
  postgres_data: